Update deploy.sh and deploy.cfg templates to match changes to repo

diff --git a/openshift_azure/roles/azure.cli.infra/templates/deploy.sh.j2 b/openshift_azure/roles/azure.cli.infra/templates/deploy.sh.j2
--- a/openshift_azure/roles/azure.cli.infra/templates/deploy.sh.j2
+++ b/openshift_azure/roles/azure.cli.infra/templates/deploy.sh.j2
@@ -4,11 +4,37 @@
 
 # Assign first argument to be Azure Resource Group
 GROUP=$1
+PRIVATE_SSH_KEY_FILE=$2
 
 # Test group variable
 if test -z $GROUP; then
-        echo "Usuage: $0 <unique name for Azure resource group>"
+        echo "Usage: $0 <unique name for Azure resource group> [ <private ssh key> ]"
         exit 1
+fi
+
+if [ -z "$PRIVATE_SSH_KEY_FILE" -o ! -f "$PRIVATE_SSH_KEY_FILE" ]; then
+  if [ -f ~/.ssh/id_rsa -a -f ~/.ssh/id_rsa.pub ]; then
+    PRIVATE_SSH_KEY_FILE=~/.ssh/id_rsa
+    PUBLIC_SSH_KEY="$( cat ~/.ssh/id_rsa.pub )"
+    echo -e "Using \e[1;33m'~/.ssh/id_rsa'\e[0m and \e[1;33m'~/.ssh/id_rsa.pub'
+\e[0m for SSH key files."
+    read -p "Do you want to use this keypair to access your azure VM
+s? (y/n)" ANSWER
+    case $ANSWER in
+      n|N)
+        echo -e "Please specify the SSH key to use, when running \e[1;33m'deploy.sh'\e[0m."
+        exit 1
+        ;;
+    esac
+  else
+    echo -e "No SSH key found in \e[1;33m'~/.ssh/id_rsa.pub'\e[0m. Generating key."
+     echo -e "Using \e[1;33m'./id_rsa'\e[0m and \e[1;33m'./id_rsa.pub'\e[0m for SSH key files."
+    ssh-keygen -t rsa -N '' -f ./id_rsa
+    PUBLIC_SSH_KEY="$(cat ./id_rsa.pub)"
+  fi
+else
+  echo -e "Using \e[1;33m'${PRIVATE_SSH_KEY_FILE}'\e[0m and \e[1;33m'${PRIVATE_SSH_KEY_FILE}.pub'\e[0m for SSH key files."
+  PUBLIC_SSH_KEY="$(cat ${PRIVATE_SSH_KEY_FILE}.pub )"
 fi
 
 OK=0
@@ -29,24 +55,24 @@ if [ -f ./deploy.cfg ]; then
 		OK=1
 	elif test -z $LOCATION; then
 		OK=1
-        elif test -z $RHN_PASSWORD; then
-                echo "Please type your red hat password, finish with [enter]:"
-                read -s
-                RHN_PASSWORD=$REPLY
+  elif test -z $RHN_PASSWORD; then
+    echo "Please type your red hat password, finish with [enter]:"
+    read -s
+    RHN_PASSWORD=$REPLY
 	fi
-        if test -z $MASTER_DNS; then
-                MASTER_DNS="${GROUP}master"
-                        if dig $MASTER_DNS.${LOCATION}.${MS_FQDN}|grep -v ";"|grep "IN A"|awk '{ print $5 }'|grep [0-9] >/dev/null; then
-                                echo "Error: $MASTER_DNS.${LOCATION}.${MS_FQDN} already exists. Select other name."
-                                exit 1
-                        fi
+  if test -z $MASTER_DNS; then
+    MASTER_DNS="${GROUP}master"
+    if dig $MASTER_DNS.${LOCATION}.${MS_FQDN}|grep -v ";"|grep "IN A"|awk '{ print $5 }'|grep [0-9] >/dev/null; then
+      echo "Error: $MASTER_DNS.${LOCATION}.${MS_FQDN} already exists. Select other name."
+      exit 1
+    fi
 	fi
-        if test -z $INFRA_DNS; then
-                INFRA_DNS="${GROUP}apps"
-                        if dig $INFRA_DNS.${LOCATION}.${MS_FQDN}|grep -v ";"|grep "IN A"|awk '{ print $5 }'|grep [0-9] >/dev/null; then
-                                echo "Error: $INFRA_DNS.${LOCATION}.${MS_FQDN} already exists. Select other name."
-                                exit 1
-                        fi
+  if test -z $INFRA_DNS; then
+    INFRA_DNS="${GROUP}apps"
+    if dig $INFRA_DNS.${LOCATION}.${MS_FQDN}|grep -v ";"|grep "IN A"|awk '{ print $5 }'|grep [0-9] >/dev/null; then
+      echo "Error: $INFRA_DNS.${LOCATION}.${MS_FQDN} already exists. Select other name."
+      exit 1
+    fi
 	fi
 	if test -z $KEYVAULTRESOURCEGROUP; then
 		KEYVAULTRESOURCEGROUP=${GROUP}
@@ -56,26 +82,6 @@ if [ -f ./deploy.cfg ]; then
 	fi
 	if test -z $KEYVAULTSECRETNAME; then
 		KEYVAULTSECRETNAME=${GROUP}SecretName
-	fi
-	if test -z "$PUBLIC_SSH_KEY"; then
-		if [ -f ~/.ssh/id_rsa.pub ]; then
-			PUBLIC_SSH_KEY="$(cat ~/.ssh/id_rsa.pub)"
-			echo "Your public key at ~/.ssh/id_rsa.pub is:"
-			echo "$PUBLIC_SSH_KEY"
-		else
-			echo "No SSH key found in ~/.ssh/id_rsa.pub. Generating key."
-			ssh-keygen
-			PUBLIC_SSH_KEY="$(cat ~/.ssh/id_rsa.pub)"
-			echo "Your key is:"
-			echo "$PUBLIC_SSH_KEY"
-		fi
-		read -p "Do you want to use this key to access your azure VMs? (y/n)" ANSWER
-		case $ANSWER in
-			n|N)
-				echo "Please fill in your public ssh key in deploy.cfg."
-				exit 1
-			;;
-		esac
 	fi
 else
 	OK=1
@@ -167,8 +173,7 @@ azure group create $GROUP $LOCATION
 azure keyvault create -u ${GROUP}KeyVaultName -g $GROUP -l $LOCATION
 
 # Put SSH private key in key vault
-# FIXME: Add option to use arbitrary key here
-azure keyvault secret set -u ${GROUP}KeyVaultName -s ${GROUP}SecretName --file "{{ ansible_ssh_private_key_file }}"
+azure keyvault secret set -u ${GROUP}KeyVaultName -s ${GROUP}SecretName --file $PRIVATE_SSH_KEY_FILE
 
 # Enable key vault to be used for deployment
 azure keyvault set-policy -u ${GROUP}KeyVaultName --enabled-for-template-deployment true
@@ -194,10 +199,10 @@ done
 
 echo "You can SSH into the cluster by accessing its bastion host:"
 bastionip=`azure network public-ip show $GROUP bastionpublicip|grep 'Ip Address'|cut -d':' -f3|grep [0-9]|sed 's/ //g'`
-echo -e "\e[1;33mssh -i {{ ansible_ssh_private_key_file }} {{ workshop_user }}@${bastionip}\e[0m\n"
+echo -e "\e[1;33mssh -i $PRIVATE_SSH_KEY_FILE ${OCP_USER}@${bastionip}\e[0m\n"
 echo "Once your SSH key has been distributed to all nodes, you can then jump passwordless from the bastion host to all nodes."
 echo "To SSH directly to the master, use port 2200:"
-echo -e "\e[1;33mssh -i {{ ansible_ssh_private_key_file }} {{ workshop_user }}@$MASTER_DNS.${LOCATION}.${MS_FQDN} -p 2200\e[0m\n"
+echo -e "\e[1;33mssh $MASTER_DNS.${LOCATION}.${MS_FQDN} -p 2200\e[0m\n"
 echo "For troubleshooting, check out /var/lib/waagent/custom-script/download/[0-1]/stdout or stderr on the nodes"
 
 
